export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIE_DESCRIPTION = "GET_MOVIE_DESCRIPTION";
export const GET_FAVORITE_MOVIES = "GET_FAVORITE_MOVIES";
export const LOADING = "LOADING";